### ISSUE TITLE
blanco linkerscherm

### ISSUE THREAD

**Issue by rdnnk** [bruvv/Waze-Editor-Dutch-helper#6]
In mij browser is na klikken van de links het linkerscherm steeds blanco. 
Dit toevoegen aan het eind van de functie helpt:   

event.preventDefault();
return false;

**Comment by bruvv** [comment]
https://github.com/bruvv/Waze-Editor-Dutch-helper/commit/47a72bc00a591010940af4f3e4a5ec4d774545e9
